Vagrant.configure("2") do |config|
  (4..5).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "alvistack/ubuntu-22.04"
      node.vm.boot_timeout = 600
      node.vm.network "private_network", ip: "192.168.56.#{i}"
      node.vm.network "private_network", ip: "192.168.57.#{i}" # Additional network interface
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = "2"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", 4]
        if i == 4
          vb.memory = "4096"  # Assign 6GB to node4
        else
          vb.memory = "2048"  # Assign 2.5GB to others
        end
      end
      node.vm.provision 'shell', path: './scripts/01_set.sh', run: 'always'
      node.vm.provision 'shell', inline: 'sudo python3 ./scripts/02_set.py', run: 'always'
      node.vm.provision 'shell', inline: 'sudo python3 ./scripts/03_set.py', run: 'always'
      node.vm.provision 'shell', inline: 'sudo python3 ./scripts/04_set.py', run: 'always'
      node.vm.provision 'shell', inline: 'sudo python3 ./scripts/05_set.py', run: 'always'
      node.vm.provision 'shell', path: './scripts/07_set.sh', run: 'always'
      node.vm.provision 'shell', path: './scripts/08_set.sh', run: 'always'
      node.vm.provision 'shell', path: './scripts/09_set.sh', run: 'always'
      node.vm.provision 'shell', path: './scripts/compute_add.sh', run: 'always'
      node.vm.provision 'shell', inline: 'sudo reboot', run: 'always'
    end
  end
end
