name: Python AIML Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AIML script
        run: |
          python main.py

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: production-artifacts
          path: |
            ./output  # Adjust this path to where your script outputs its results
