name: Simple Python Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    #   - name: Set up Python
    #     uses: ./.github/actions/setup-python
    #     with:
    #       python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
           echo hello; echo hello; if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
